import { $, api, esc, state, toast } from './core.js';

let records = [], selectedRun = '';
const fmtTime = v => v ? new Date(v * 1000).toLocaleString() : '-';
const fmtMs = v => v == null ? '-' : (v >= 1000 ? (v / 1000).toFixed(2) + 's' : v + 'ms');
const json = v => JSON.stringify(v ?? null, null, 2);
const usage = v => { const i=v?.prompt_tokens??v?.input_tokens??0,o=v?.completion_tokens??v?.output_tokens??0;return `${i} / ${o} / ${v?.total_tokens??i+o}`; };
const badge = s => `<span class="log-status ${esc(s)}">${esc({success:'成功',error:'失败',running:'运行中'}[s]||s)}</span>`;
const section = (title,value,open=false) => `<details class="log-section" ${open?'open':''}><summary>${esc(title)}</summary><pre>${esc(json(value))}</pre></details>`;

function syncProviders(){const n=$('log-filter-provider'),v=n.value;n.innerHTML='<option value="">全部接口</option>'+(state.providers||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.name||x.id)}</option>`).join('');n.value=v;}
function renderStats(s={}){$('log-total').textContent=s.total??0;$('log-success-rate').textContent=(s.success_rate??0)+'%';$('log-average').textContent=fmtMs(s.average_duration_ms??0);$('log-tokens').textContent=s.total_tokens??0;}
function renderList(){const box=$('log-list');if(!records.length){box.innerHTML='<div class="empty">暂无调用日志</div>';return;}box.innerHTML=records.map(x=>`<button class="log-row ${selectedRun===x.run_id?'active':''}" data-run-id="${esc(x.run_id)}" type="button"><span class="log-row-main"><b>${esc(x.provider_name||x.provider_id||'未选择接口')} · ${esc(x.model||'-')}</b><small>${esc(x.consumer_plugin||x.kind||'系统')} · ${esc(fmtTime(x.started_at))}</small></span><span class="log-row-meta">${badge(x.status)}<small>${esc(fmtMs(x.duration_ms))} · ${x.tool_count||0} 工具</small></span></button>`).join('');box.querySelectorAll('.log-row').forEach(b=>b.onclick=()=>loadDetail(b.dataset.runId));}
function renderDetail(x){const box=$('log-detail');if(!x){box.innerHTML='<div class="empty">选择一条调用查看完整请求、响应与工具记录</div>';return;}const attempts=(x.attempts||[]).map((a,i)=>`<article class="attempt"><div class="attempt-head"><b>请求 ${i+1} · ${esc(a.provider_name||a.provider_id)} / ${esc(a.model)}</b>${badge(a.status)}</div><div class="log-facts"><span>HTTP ${esc(a.http_status??'-')}</span><span>首字 ${esc(fmtMs(a.ttfb_ms))}</span><span>耗时 ${esc(fmtMs(a.duration_ms))}</span><span>速度 ${a.tokens_per_second==null?'-':esc(a.tokens_per_second+' token/s')}</span><span>请求 ${esc(a.request_bytes??0)} B</span><span>响应 ${esc(a.response_bytes??0)} B</span><span>Token ${esc(usage(a.usage))}</span></div>${section('请求地址与请求头',{endpoint:a.endpoint,headers:a.request_headers})}${section('请求正文',a.request,true)}${section('响应头',a.response_headers)}${section('响应正文',a.response,true)}${a.error?`<pre class="log-error">${esc(a.error)}</pre>`:''}</article>`).join('');const tools=(x.tools||[]).map((t,i)=>`<article class="attempt tool-attempt"><div class="attempt-head"><b>工具 ${i+1} · ${esc(t.name)}</b>${badge(t.status)}</div><div class="log-facts"><span>耗时 ${esc(fmtMs(t.duration_ms))}</span></div>${section('调用参数',t.arguments,true)}${section('执行结果',t.result,true)}${t.error?`<pre class="log-error">${esc(t.error)}</pre>`:''}</article>`).join('');box.innerHTML=`<div class="log-detail-head"><div><h3>${esc(x.run_id)}</h3><p>${esc(fmtTime(x.started_at))} · ${esc(x.session_id||'无会话')} · ${esc(x.consumer_plugin||x.kind)}</p></div>${badge(x.status)}</div><div class="log-facts prominent"><span>总耗时 ${esc(fmtMs(x.duration_ms))}</span><span>首字 ${esc(fmtMs(x.ttfb_ms))}</span><span>速度 ${x.tokens_per_second==null?'-':esc(x.tokens_per_second+' token/s')}</span><span>Token ${esc(usage(x.usage))}</span><span>请求 ${x.attempts?.length||0} 次</span><span>工具 ${x.tools?.length||0} 次</span></div>${x.error?`<pre class="log-error">${esc(x.error)}</pre>`:''}${section('调用入口参数',x.request)}${attempts||'<div class="empty">没有上游请求记录</div>'}${tools?'<h3 class="log-subtitle">工具调用</h3>'+tools:''}${section('最终响应',x.response)}${section('运行事件',x.events||[])}`;}
export async function loadDetail(id){selectedRun=id;renderList();$('log-detail').innerHTML='<div class="empty">加载详情...</div>';try{renderDetail(await api('/logs?run_id='+encodeURIComponent(id)));}catch(e){toast(e.message,true);}}
export async function loadLogs(first=false){syncProviders();const q=new URLSearchParams({limit:'200'}),s=$('log-filter-status').value,p=$('log-filter-provider').value,k=$('log-search').value.trim();if(s)q.set('status',s);if(p)q.set('provider',p);if(k)q.set('search',k);const d=await api('/logs?'+q);records=d.items||[];renderStats(d.stats||{});renderList();if((first||!selectedRun)&&records.length)await loadDetail(records[0].run_id);if(!records.length)renderDetail(null);}
export function bindLogs(){$('log-refresh').onclick=()=>loadLogs().catch(e=>toast(e.message,true));$('log-clear').onclick=async()=>{if(!confirm('确定清空全部 AI LLM 调用日志？'))return;try{await api('/logs',{method:'DELETE'});selectedRun='';await loadLogs();toast('调用日志已清空');}catch(e){toast(e.message,true);}};$('log-filter-status').onchange=$('log-filter-provider').onchange=()=>loadLogs(true).catch(e=>toast(e.message,true));let timer;$('log-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>loadLogs(true).catch(e=>toast(e.message,true)),300);};}
